### ISSUE TITLE
관리자 설정에서 페이지 당 보여줄 상품 갯수 수정 후 서버 재시작하면 미반영

### ISSUE THREAD

**Issue by ybin0823** [HelloMocca/YDbaobao#136]

**Comment by ybin0823** [comment]
서버를 시작할 때 CommonUtil pagePerPage 변수를 AdminConfig DB에 저장된 adminDisplayProducts 숫자로 초기화할 필요가 있음

**Comment by hwiba** [comment]
> > 서버를 시작할 때 CommonUtil pagePerPage 변수를 AdminConfig DB에 저장된 adminDisplayProducts 숫자로 초기화할 필요가 있음

DB에서 꺼내온 값을 매번 적용해야지 상품 보여주는 숫자를 바꿨다고 관리자가 서버를 재시작하는 것이 옳은지?

**Comment by hwiba** [comment]
매 변경시마다 pagePerPage에 적용시켜 메모리 상에 값을 올려서 DB 접근을 축소시키는 것이 목적인 건가?

**Comment by ybin0823** [comment]
> 매 변경시마다 pagePerPage에 적용시켜 메모리 상에 값을 올려서 DB 접근을 축소시키는 것이 목적인 건가?

현재 search 부분에서 검색할 때마다 adminConfigService에서 adminDisplayProducts 숫자를 DB에서 불러오는데, DB 커넥션 처럼 자원을 많이 소모하는 부분을 굳이 불필요하게 사용할 필요가 있을까?

CommonUtil.productsPerPage 에서 참조해도 충분할 것 같은데. 다만 이슈에서 처럼 처음에 서버를 시작할 때만 DB값으로 초기화를 해주면 될 듯
