### ISSUE TITLE
페이지 인덱싱 prev 버튼을 누를 시 21 ~ 30 패턴일 때 20으로 가는게 아니라 11로 감.

### ISSUE THREAD

**Issue by hwiba** [HelloMocca/YDbaobao#157]

**Comment by ybin0823** [comment]
이 부분은 버그는 아니고 구현 상황단계에서 prev 누르면 앞에 블럭에 첫 페이지로 가도록 구현했음.

**Comment by hwiba** [comment]
그게 일반적인가?

**Comment by ybin0823** [comment]
딱히 어느 쪽이든 상관은 없을 듯. prev 눌렀을 때 이전 블럭의 마지막 페이지로 가는 페이징도 있고, 첫 페이지로 가는 페이징도 있어서

**Comment by hwiba** [comment]
ok
