### ISSUE TITLE
상품 리스트 보기 캐시 적용하기(현재 55만개에서 최신순으로 정렬해서 16개 띄우는데 메인페이지 뜨는데만해도 3초가 걸림)

### ISSUE THREAD

**Issue by hwiba** [HelloMocca/YDbaobao#76]

**Comment by ybin0823** [comment]
과연 실제 쇼핑몰이 55만개의 데이터가 들어갈 지 그 여부 확인이 필요할 것 같네요~
금요일에 물어봐야 할 것 같습니다.

듣기로는 시즌이 지난 상품은 삭제한다는 얘기도 있었던 것 같네요
